# 导航栏
menu:
  Tags: /tags
  About: /about

# favicon 生成：https://favicon.io/favicon-converter/
# 站点图标路径
favicon: /favicon/favicon.ico

# 头部 Logo
logo: /favicon/favicon.png


# 站点验证
site_verification:
  sougou: Ya613VDsLE  # https://zhanzhang.sogou.com/index.php/dashboard/index
  search360: cede68bb0b1448f4d5dcc6cdbdb1239d # https://zhanzhang.so.com/sitetool/site_manage
  baidu: CXJVSO2lgq # https://ziyuan.baidu.com/dashboard/index

# 站点推送
auto_push:
  baidu: true # https://ziyuan.baidu.com/college/courseinfo?id=267&page=2#h2_article_title19

# 评论
comments:
  cusdisId: 1cb3e939-8077-4b08-b822-85d5b6ab403d  # https://cusdis.com/