# 导航栏
menu:
  categories: /categories
  tags: /tags
  about: /about

plugins:
  googleAnalytics: UA-121105508-1 # google 分析

  scrollToTop: true # 滚动到顶部
  scrollSmooth: false # 开启平滑滚动

  # 评论
  comments:
    enable: true # 是否启用
    repo: zowiegong/hexo-blog # repo