# 基本信息
repo: zowiegong/hexo-blog
mail: zowiegong@gmail.com

# 导航栏
menu:
  categories: /categories
  tags: /tags
  about: /about

# 插件
plugins:
  # google 分析
  googleAnalytics: UA-121105508-1

  # 滚动到顶部
  scrollToTop: true
  # 开启平滑滚动
  scrollSmooth: false

  # 评论，评论基于 utteranc.es 启用前请先安装 https://github.com/apps/utterances 在指定 repo
  comments:
    enable: true # 是否启用评论
    repo: zowiegong/hexo-blog # utterances app 所在 repo